### ISSUE TITLE
build vanilla es5 for npm /  browserify

### ISSUE THREAD

**Issue by forresto** [flowbased/fbp-manifest#18]
Now trying to browserify noflo gives: 

> stderr: Error: Cannot find module './src/list' from '.../node_modules/noflo/node_modules/fbp-manifest'

Can we build js for browserify simplicity?

**Comment by bergie** [comment]
@forresto any particular reason to use browserify instead of webpack?

Also, this module deals with the filesystem, so in general it doesn't make much sense to build it for the browser. Instead, utilize it at build stage to generate a `fbp.json` containing available components, and then use that file to register components to be included in the browser build. This is what grunt-noflo-browser does.

**Comment by forresto** [comment]
Noflo depends on this: https://www.npmjs.com/browse/depended/fbp-manifest

**Comment by bergie** [comment]
@forresto yep, but only in the Node.js component loader. With webpack we swap that file with a custom componentloader we generate for browser usage:

https://github.com/noflo/grunt-noflo-browser/blob/master/src/webpack.js#L27

If you're concerned about the browserify build of the-graph, that now can depend on just https://github.com/flowbased/fbp-graph instead of NoFlo

**Comment by vespakoen** [comment]
Same here, I want to use noflo in NW.js, the `require('coffee-script/register');` doesn't seem to work in that environment so it crashes.

Compiling to ES5 seems a very logical thing to do, it also speeds up the initial start time.

Browserify is a perfectly valid alternative for webpack, even when not building for the browser.
